name: BuildDocFX

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x

      - run: dotnet tool update -g docfx

      - name: Build documents
        run: |
          cp Readme.md docfx_project/docs/intro.md
          docfx docfx_project/docfx.json

      - name: Check paths
        run: |
          ls
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/*
          ls $GITHUB_WORKSPACE/docfx_project/_site

      - name: Upload to the temporary place.
        uses: actions/upload-artifact@v4
        with:
          path: docfx_project/_site
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docfx_project/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
